version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.5.0
    working_directory: ~/repo

jobs:
  terraform-setup:
    executor: terraform-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache python3 py3-pip
            pip3 install awscli
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - terraform-setup
